# -*- coding: utf-8 -*-
"""FrontEnd Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1XhG-M010XlMH_4qrhGQWBhd0bJF_o2
"""

# Git Repo example: https://github.com/dataprofessor/population-dashboard/tree/master
# Dashboard example: https://population-dashboard.streamlit.app/?ref=blog.streamlit.io

import sys
import os

#!pip install streamlit
import streamlit as st
import pandas as pd
#!pip install pandas
#import altair as alt
#import plotly.express as px


#Cloning the github repo
# Clone the GitHub repo if not already cloned
if not os.path.exists('DS-440---Group-2'):
    os.system('git clone https://github.com/AmaanRai1/DS-440---Group-2.git')

# Convert Jupyter notebook to Python script if necessary
if not os.path.exists('DS-440---Group-2/strategies.py'):
    os.system('jupyter nbconvert --to script DS-440---Group-2/strategies.ipynb')

# Add repo directory to system path
sys.path.append('DS-440---Group-2')


# strategies is what file we want to use from the git repo
#from strategies import apply_indicator  # apply_indicator is supposed to be a function in the strategies code


# Page configuration
st.set_page_config(
    page_title="Technical Indicator Dashboard",
    layout="wide",
    initial_sidebar_state="expanded")

#alt.themes.enable("dark")

# Input boxes
with st.sidebar:
    st.title('Technical Indicator Dashboard')

    stock_ticker_lst = ['dji', 'gdaxi', 'ibex']
    selected_stock_ticker = st.selectbox('Select a stock', stock_ticker_lst)

    # Start and end date selections
    start_date_lst = ['']  # You need to populate these lists properly
    selected_start_date = st.selectbox('Select a start date', start_date_lst)

    end_date_lst = ['']
    selected_end_date = st.selectbox('Select an end date', end_date_lst)

    # Technical indicators selection
    st.markdown("### Select Technical Indicators:")
    selected_technicalindicators = st.radio('Choose a technical indicator', ('RSI (Relative Strength Index)', 'MACD (Triple Exponential Moving Average)', 'TEMA (Triple Exponential Moving Average)'))
    
    # Selectbox to decide whether to pair indicator with ML model
    st.markdown("### Pair with Machine Learning Model?")
    pair_option = st.selectbox(
        "Would you like to pair the selected technical indicator with the chosen ML model?",
        ("Yes", "No")
    )

    # Machine learning models selection
    st.markdown("### Select Machine Learning Model:")
    selected_model = st.radio('Choose a model to pair with indicators', ('Linear Regression', 'LSTM'))


# Logic for Execution
#if execute:
 #   if pair_option == "Yes":
  #      st.write(f"Running {selected_indicator} paired with {selected_model} model...")
        # Add code to run the hybrid model with the selected indicator and ML model
   # else:
    #    st.write(f"Running {selected_indicator} without pairing...")
        # Add code to run the selected indicator without pairing with ML model

